upadte ci

diff --git a/.github/actions/cargo/action.yml b/.github/actions/cargo/action.yml
--- a/.github/actions/cargo/action.yml
+++ b/.github/actions/cargo/action.yml
@@ -37,6 +37,26 @@ runs:
       run: |
         cargo build --release -p simple-runtime
 
+    - name: Symlink libcudnn.so to libcudnn.so.9 and export LD_LIBRARY_PATH
+      if: ${{ inputs.os == 'linux' }}
+      shell: bash
+      run: |
+        libfile=$(find target/release -type f -name 'libcudnn.so' | head -n1)
+
+        if [ -n "$libfile" ]; then
+          echo "Found libcudnn at $libfile"
+
+          # Use /usr/local/lib since it's already in the default library search path
+          sudo mkdir -p /usr/local/lib
+
+          sudo ln -sf "$libfile" /usr/local/lib/libcudnn.so.9
+          sudo ldconfig   # refresh the dynamic linker cache
+
+          echo "✅ Linked libcudnn globally: /usr/local/lib/libcudnn.so.9"
+        else
+          echo "❌ libcudnn.so not found in target/release"
+          exit 1
+        fi
     - name: Prepare artifacts
       shell: bash
       run: |
@@ -79,8 +99,10 @@ runs:
               done
         fi
 
-        find target/release -maxdepth 1 -type f -name 'onnxruntime_providers_*.*' \
-          -exec cp {} artifact/ \;
+        find target/release -maxdepth 1 -type f \
+                  ! -name '.*' \
+                  -name '*onnxruntime_providers*.so*' \
+                  -exec cp -u {} artifact/ \; || true
 
     - name: Upload artifacts
       uses: actions/upload-artifact@v4
